tasks = {
    "submit_2": {
        "TYPE": 'submit',
        "ASSIGNMENT_ID": '_147_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 2,
        "NUMBER_OF_SUBMISSION":2,
        "SECTION": '2016R1-NURS1151-',
        "MARKER": 'b00001Last,b00001First',
    },
    "submit_3": {
        "TYPE": 'submit',
        "ASSIGNMENT_ID": '_147_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 1,
        "NUMBER_OF_SUBMISSION":10,
        "SECTION": '2016R1-NURS1151-',
        "MARKER": 'b00001Last,b00001First',
    },
    "submit_4": {
        "TYPE": 'submit',
        "ASSIGNMENT_ID": '_147_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 1,
        "NUMBER_OF_SUBMISSION":10,
        "SECTION": '2016R1-NURS1151-T02',
        "MARKER": 'wlRG 7O2 Mfe',
    },
    "submit_5": {
        "TYPE": 'submit',
        "ASSIGNMENT_ID": '_147_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 1,
        "NUMBER_OF_SUBMISSION":10,
        "SECTION": '2016R1-NURS1151-T05',
        "MARKER": 'BOCE KSJ JOC',
    },
    "submit_6": {
        "TYPE": 'submit',
        "ASSIGNMENT_ID": '_147_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 1,
        "NUMBER_OF_SUBMISSION":10,
        "SECTION": '2016R1-NURS1151-T06',
        "MARKER": 'BOCE KSJ JOC',
    },
    "submit_7": {
        "TYPE": 'submit',
        "ASSIGNMENT_ID": '_150_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 1,
        "NUMBER_OF_SUBMISSION": 1,
        "SECTION": '2016R1-NURS1151-',
        "MARKER": 'wlRG 7O2 Mfe',
    },
    "submit_8": {
        "TYPE": 'submit',
        "ASSIGNMENT_ID": '_150_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 1,
        "NUMBER_OF_SUBMISSION": 2,
        "SECTION": '',
        "MARKER": 'wlRG 7O2 Mfe'
    },
    "submit_uat_individual_230_1": {
        "TYPE": 'submit',
        "ASSIGNMENT_ID": '_230_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 3,
        "NUMBER_OF_SUBMISSION": 3,
        "SECTION": '',
        "MARKER": 'wlRG 7O2 Mfe'
    },
    "submit_uat_group_234_1": {
        "TYPE": 'submit',
        "ASSIGNMENT_ID": '_234_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 3,
        "NUMBER_OF_SUBMISSION": 5,
        "SECTION": '',
        "MARKER": 'wlRG 7O2 Mfe'
    },
    "submit_stress_test_individual_asg_1": {
        "TYPE":'submit',
        "ASSIGNMENT_ID": 'Stress Test Individual Assignment 1',
        "WAIT_TIME": 120,
        "SLEEP_TIME": 2,
        "NUMBER_OF_SUBMISSION": 1000,
        "SECTION": '',
        "MARKER": 'b00050Last,b00050First'
    },
    "view_1": {
        "TYPE": 'view',
        "ASSIGNMENT_ID": '_145_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 2,
        "NUMBER_OF_REFRESH":5,
    },
    "view_2": {
        "TYPE": 'view',
        "ASSIGNMENT_ID": '_148_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 4,
        "NUMBER_OF_REFRESH":30,
    },
    "view_3": {
        "TYPE": 'view',
        "ASSIGNMENT_ID": '_147_1',
        "WAIT_TIME": 60,
        "SLEEP_TIME": 1,
        "NUMBER_OF_REFRESH":10,
    }
}
